language: generic
sudo: required
servies:
  - docker

before_install:
  - docker build -t rahul6004/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rahul6004/react-test npm test

after_success:
  - docker build -t rahul6004/multi-client ./client
  - docker build -t rahul6004/multi-client ./nginx
  - docker build -t rahul6004/multi-client ./server
  - docker build -t rahul6004/multi-client ./worker


